/* Generated By:JavaCC: Do not edit this line. GrammarParserTreeConstants.java Version 5.0 */
package parser;

public interface GrammarParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTNFASET = 1;
  public int JJTEXPRESSIONSET = 2;
  public int JJTVOID = 3;
  public int JJTSUBNFA = 4;
  public int JJTTERM = 5;
  public int JJTOPERATOR = 6;


  public String[] jjtNodeName = {
    "Start",
    "NFASet",
    "ExpressionSet",
    "void",
    "SubNFA",
    "Term",
    "Operator",
  };
}
/* JavaCC - OriginalChecksum=57a3b2fe704a2ccbde89b7d399fbd326 (do not edit this line) */
