/* Generated By:JJTree&JavaCC: Do not edit this line. GrammarParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GrammarParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTERVAL = 4;
  /** RegularExpression Id. */
  int OPERATOR = 5;
  /** RegularExpression Id. */
  int INTEGER = 6;
  /** RegularExpression Id. */
  int LF = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int DOT = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INTERVAL>",
    "<OPERATOR>",
    "<INTEGER>",
    "\"\\n\"",
    "<IDENTIFIER>",
    "\".\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
